#ifndef GUARD_CONSTANTS_CADMIUM_CRIES_H
#define GUARD_CONSTANTS_CADMIUM_CRIES_H

#include "hoenn_cries.h"

enum
{
	CRY_RAINER = CRY_CHIMECHO + 1,
	CRY_SAPUSAUR,
	CRY_CHARCOLT,
	CRY_PETILIL,
	CRY_LILLIGANT,
	CRY_UNOWN_KING,
};

#endif