name: CI

on:
  push:
    branches: [ master, trainer-fly ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install binutils
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi libpng-dev python3

      - name: Build
        run: |
          make -j${nproc} all

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: FRLGV.gba
          path: pokefirered.gba
          retention-days: 2
          archive: false
